"""Stage-1 pretraining corpora.

Every corpus is an array of 5-s windows (V, 500, 9) in physical sensor units, saved
as float16 plus a label vector recording which class each window was derived from
(the labels are never used by the reconstruction objective; they are only needed
for the class-balance table, S-19).

Volume unit R = number of REAL minority-class (drink + eat) windows of the TRAINING
subjects. A corpus of "k R" has k * R windows, split equally among the classes in
its scope ("minority" = drink, eat; "all" = drink, eat, other).

Corpus kinds
------------
diffusion   windows generated by PaD-TS (attention or BiGRU variant). Generators
            that produce W < 500 steps are stitched by concatenating consecutive
            generated segments, as in the legacy pipeline.
augment     classical augmentation of real training windows: jitter + per-axis
            scaling + a random 3-D rotation applied to each sensor triad.   (R1-06a)
noise       i.i.d. multivariate Gaussian with the per-class mean and 9x9 covariance
            of the real training windows (a naive generator).                  (R1-06b)
surrogate   multivariate phase-randomised surrogates of real training windows:
            the same random phases on all 9 axes keep every auto- and
            cross-spectrum but destroy the temporal structure.                  (R1-06c)
real        the real training windows themselves, no extra volume (unlabelled
            self-supervised pretraining on real data only).
"""
import math
import os

import numpy as np

from . import N_FEATURES, N_TIMESTEPS
from .io import take
from .utils import write_json

CLASS_IDS = {"drink": 0, "eat": 1, "other": 2}
SCOPES = {"minority": ["drink", "eat"], "all": ["drink", "eat", "other"]}


def class_train_indices(meta, split):
    train = meta["subject"].isin(split["train"]).to_numpy()
    labels = meta["label"].to_numpy()
    return {c: np.flatnonzero(train & (labels == k)) for c, k in CLASS_IDS.items()}


def volume_unit(meta, split):
    idx = class_train_indices(meta, split)
    return int(len(idx["drink"]) + len(idx["eat"]))


def allocate(total, classes):
    base = total // len(classes)
    counts = {c: base for c in classes}
    for c in classes[: total - base * len(classes)]:
        counts[c] += 1
    return counts


# ---------------------------------------------------------------- transforms
def _rotation_matrices(rng, n, max_deg):
    a = np.deg2rad(rng.uniform(-max_deg, max_deg, size=(n, 3)))
    cx, cy, cz = np.cos(a).T
    sx, sy, sz = np.sin(a).T
    R = np.zeros((n, 3, 3))
    R[:, 0, 0] = cy * cz
    R[:, 0, 1] = -cy * sz
    R[:, 0, 2] = sy
    R[:, 1, 0] = sx * sy * cz + cx * sz
    R[:, 1, 1] = -sx * sy * sz + cx * cz
    R[:, 1, 2] = -sx * cy
    R[:, 2, 0] = -cx * sy * cz + sx * sz
    R[:, 2, 1] = cx * sy * sz + sx * cz
    R[:, 2, 2] = cx * cy
    return R


def augment(x, rng, axis_std, jitter=0.05, scale=0.1, max_deg=15.0):
    """x: (n, 500, 9) physical units."""
    n = len(x)
    x = x + rng.normal(0.0, 1.0, size=x.shape) * (jitter * np.asarray(axis_std))
    x = x * rng.normal(1.0, scale, size=(n, 1, N_FEATURES))
    R = _rotation_matrices(rng, n, max_deg)
    out = np.empty_like(x)
    for s in range(0, N_FEATURES, 3):  # acc, gyr, mag triads share the rotation
        out[:, :, s:s + 3] = np.einsum("nij,ntj->nti", R, x[:, :, s:s + 3])
    return out


def phase_surrogate(x, rng):
    F = np.fft.rfft(x, axis=1)
    phases = rng.uniform(0, 2 * np.pi, size=(len(x), F.shape[1], 1))
    phases[:, 0] = 0.0
    if x.shape[1] % 2 == 0:
        phases[:, -1] = 0.0
    return np.fft.irfft(F * np.exp(1j * phases), n=x.shape[1], axis=1)


def gaussian_fit(X, idx, max_windows=20000, rng=None):
    rng = rng or np.random.default_rng(0)
    sel = idx if len(idx) <= max_windows else rng.choice(idx, max_windows, replace=False)
    flat = take(X, sel).reshape(-1, N_FEATURES).astype(np.float64)
    return flat.mean(0), np.cov(flat, rowvar=False)


# ------------------------------------------------------------------ builders
class ConcatArray:
    """Read-only concatenation of several .npy memmaps along axis 0 (sampling shards)."""

    def __init__(self, paths):
        self.parts = [np.load(p, mmap_mode="r") for p in paths]
        self.bounds = np.cumsum([0] + [len(p) for p in self.parts])
        self.shape = (int(self.bounds[-1]),) + self.parts[0].shape[1:]

    def __len__(self):
        return self.shape[0]

    def __getitem__(self, sl):
        start, stop, _ = sl.indices(len(self))
        out = []
        for part, lo, hi in zip(self.parts, self.bounds[:-1], self.bounds[1:]):
            a, b = max(start, lo), min(stop, hi)
            if a < b:
                out.append(np.asarray(part[a - lo:b - lo]))
        return np.concatenate(out, axis=0)


def stitch(segments, n_windows, offset=0):
    """(M, W, 9) generated segments -> (n_windows, 500, 9), consecutive segments."""
    W = segments.shape[1]
    k = math.ceil(N_TIMESTEPS / W)
    need = offset + n_windows * k
    if need > len(segments):
        raise ValueError("need %d generated segments of length %d, only %d available"
                         % (need, W, len(segments)))
    block = np.asarray(segments[offset:need], dtype=np.float32)
    return block.reshape(n_windows, k * W, N_FEATURES)[:, :N_TIMESTEPS]


def build(kind, out_dir, X, meta, split, multiplier, scope="minority", seed=0,
          generated=None, axis_std=None, chunk=5000):
    """Write corpus.npy (float16), labels.npy (int8) and manifest.json into out_dir."""
    os.makedirs(out_dir, exist_ok=True)
    rng = np.random.default_rng(seed)
    R = volume_unit(meta, split)
    idx = class_train_indices(meta, split)
    classes = SCOPES[scope]
    if kind == "real":
        sources = np.concatenate([idx[c] for c in classes])
        counts = {c: int(len(idx[c])) for c in classes}
        total = len(sources)
    else:
        total = int(round(multiplier * R))
        counts = allocate(total, classes)
    corpus = np.lib.format.open_memmap(os.path.join(out_dir, "corpus.npy"), mode="w+",
                                       dtype=np.float16, shape=(total, N_TIMESTEPS, N_FEATURES))
    labels = np.empty(total, dtype=np.int8)
    pos = 0
    for c in classes:
        n_c = counts[c]
        if kind == "noise":
            mu, cov = gaussian_fit(X, idx[c], rng=rng)
        for s in range(0, n_c, chunk):
            m = min(chunk, n_c - s)
            if kind == "real":
                block = take(X, idx[c][s:s + m])
            elif kind == "diffusion":
                block = stitch(generated[c], m, offset=s * math.ceil(N_TIMESTEPS / generated[c].shape[1]))
            elif kind == "noise":
                block = rng.multivariate_normal(mu, cov, size=(m, N_TIMESTEPS))
            else:
                src = take(X, rng.choice(idx[c], size=m, replace=True))
                if kind == "augment":
                    block = augment(src, rng, axis_std)
                elif kind == "surrogate":
                    block = phase_surrogate(src, rng)
                else:
                    raise ValueError("unknown corpus kind %r" % kind)
            corpus[pos:pos + m] = np.clip(block, -6e4, 6e4).astype(np.float16)
            labels[pos:pos + m] = CLASS_IDS[c]
            pos += m
    corpus.flush()
    np.save(os.path.join(out_dir, "labels.npy"), labels)
    manifest = {"kind": kind, "scope": scope, "multiplier": multiplier, "volume_unit_R": R,
                "n_windows": int(total), "per_class": counts, "seed": seed,
                "real_train_windows_per_class": {c: int(len(v)) for c, v in idx.items()}}
    write_json(os.path.join(out_dir, "manifest.json"), manifest)
    return manifest
